language: generic
services: docker
addons:
  apt:
    packages:
    - docker-ce
os: linux

before_install:
- docker pull base/archlinux
- docker run --detach --name=extlint-build --volume=$TRAVIS_BUILD_DIR:/code base/archlinux bash -c "while true; do sleep 60; done"
install:
- docker exec -w /code extlint-build bash .travis/install-dependencies.sh

script:
- docker exec -w /code extlint-build bash .travis/package.sh
- docker cp extlint-build:/code/extlint.tar.gz extlint.tar.gz
after_script:
- docker stop -t 1 extlint-build
