language: rust
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - opam
os: linux

install:
- opam init -a
- eval `opam config env`
- opam switch 4.06.0
- eval `opam config env`
- opam install -y core ocamlfind ocaml-compiler-libs

script:
- make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: extlint.tar.gz
  skip_cleanup: true
  on:
    tags: true
