[package]
name = "pretty-errors"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]

[dependencies]
ansi_term = { version = "0.11.0", optional = true }
lazy_static = { version = "1.0.0", optional = true }

[features]
color = ["ansi_term", "lazy_static"]
default = ["color"]
