[package]
description = "A library for parsing OCaml."
name = "ocaml-ast"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
sparkly = "0.1.4"

[build-dependencies]
cc = "1.0.4"
lazy_static = "1.0.0"

[[bin]]
name = "json_of_ocaml"
path = "src/bin/json_of_ocaml.rs"
